version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stderr
loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
  botocore:
    level: INFO
    handlers: [console]
    propagate: no
  urllib3:
    level: INFO
    handlers: [console]
    propagate: no
  charset_normalizer:
    level: INFO
    handlers: [console]
    propagate: no
  bluepyemodel:
    level: INFO
    handlers: [console]
    propagate: no
  bluepyopt:
    level: INFO
    handlers: [console]
    propagate: no
  efel:
    level: INFO
    handlers: [console]
    propagate: no
  __main__:
    level: INFO
    handlers: [console]
    propagate: no
  fontTools:
    level: WARNING
    handlers: [console]
    propagate: no
root:
  level: ERROR
  handlers: [console]
  propagate: yes
